### ISSUE TITLE
Prompt for password and/or repository if they are not provided via restic env vars or redu cmd line arguments

### ISSUE THREAD

**Issue by drdo** [drdo/redu#27]

**Comment by eugenesan** [comment]
It's not a perfect solution but I am using the following wrapper script to manage password input and exclusion list output.

It's untested on Darwin but works on Linux.

Please find the script attached.
[redu.sh.txt](https://github.com/user-attachments/files/16352543/redu.sh.txt)

**Comment by drdo** [comment]
The way I use it myself is I just have `RESTIC_REPOSITORY` and `RESTIC_PASSWORD_COMMAND` set and just call `redu`.

Still, I think it would be nice to perhaps prompt the user for the password just like restic does when the password is not set via other means.

Additionally, the other methods that flags that restic supports for setting repo and password via files should probably be added as well.

**Comment by drdo** [comment]
On the wrapper script, I'm glad it works for you, thanks for sharing.

I think it makes sense for personal use but I do feel like actually getting into the business of managing the passwords using OS provided keychains is a little off scope for `redu` and should be left for the user to decide what they want to do.

**Comment by eugenesan** [comment]
> The way I use it myself is I just have `RESTIC_REPOSITORY` and `RESTIC_PASSWORD_COMMAND` set and just call `redu`.
> 
> Still, I think it would be nice to perhaps prompt the user for the password just like restic does when the password is not set via other means.
> 
> Additionally, the other methods that flags that restic supports for setting repo and password via files should probably be added as well.

I personally am against using environmental variables and files containing secrets.
On Linux it is possible to pass passwords using file descriptors.
_https://www.gnu.org/software/bash/manual/html_node/Process-Substitution.html_
In bash you can do something like:
```
MYPASS="secret"
mycmd --password-file <(echo "${MYPASS}")
```
It creates temporary file descriptor, writes the password to it and passes the descriptor as a filename (for example ``/dev/fd/63``).
It should be possible to replicate in Rust. 
It might be also possible on Darwin and Windows (since both are Posix compliant).
That method would be a much better solution from security stand point.

**Comment by drdo** [comment]
Oh I don't have my actual password in any environment variable.

I have something like `RESTIC_PASSWORD_COMMAND='security find-generic-password -s restic -a personal -w'` which uses the MacOS keychain.
